### ISSUE TITLE
random things that crossed my mind

### ISSUE THREAD

**Issue by jgrewe** [G-Node/gin-ui#58]
The firefox title is not set, i.e. when the GIN tab is open, firefox show "mozilla firefox" in the task bar and the frame title, something like G-Node GIN or similar would be nicer,

Firefox offered to remember the password upon account creation but is does not show the login as account name but the country, i.e. the last text field before the password. Is this under your control? Can this be changed to show the account name?

In the activation screen, the G-Node logo is a link but does not lead anywhere.

Same page, a link back to the sign-in page would be great

some help/information in the ssh key registration page would be good for the more naive user, why would I need it, why should I use it and how can I get an ssh key

**Comment by achilleas-k** [comment]
Breaking this into multiple individual issues.

> The firefox title is not set, i.e. when the GIN tab is open, firefox show "mozilla firefox" in the task bar and the frame title, something like G-Node GIN or similar would be nicer.

This is an issue with the auth server not specifying a title for its pages. Created issue G-Node/gin-auth#118.

> Firefox offered to remember the password upon account creation but is does not show the login as account name but the country, i.e. the last text field before the password. Is this under your control? Can this be changed to show the account name?

As you mentioned, this is probably an issue with the order of fields in the sign up form. Created issue #61.

> In the activation screen, the G-Node logo is a link but does not lead anywhere.

This has been fixed but it hasn't been deployed yet.

> Same page, a link back to the sign-in page would be great

Good idea. Created issue #62.

> some help/information in the ssh key registration page would be good for the more naive user, why would I need it, why should I use it and how can I get an ssh key

We generally need information text in a lot of places. Created issue #63.

**Comment by mpsonntag** [comment]
All points in this issue have been addressed or moved to their own issues. Closing.
