### ISSUE TITLE
Reload of page fails with 404 or gives surprising results

### ISSUE THREAD

**Issue by jgrewe** [G-Node/gin-ui#70]
e.g. reloading a repository main page results in 
"Nothing here. Move along."

reloading the "files" page to check for updates as I push files ends with 404

If reloading is a problem, what about a refresh button?

**Comment by mpsonntag** [comment]
I think I narrowed it down to that this only happens, when a repository is private.

I think it is a race condition of variables in different vue components, that are not passed to their child components in time, since many of the variables are fetched using promises...
